version: '3.3'
services:
 web_app:
   build: ./web_app
   volumes:
     - .:/web_app
   ports:
     - "8000:8000"
   depends_on:
     - pytest_db
     - loop
   logging:
     driver: "json-file"
     options:
       max-size: "10k"
       max-file: "1"
 loop:
   build: ./loop
   volumes:
     - .:/loop
   ports:
     - "8080:8080"
 pytest_db:
   image: mongo
   restart: always
   environment:
     MONGO_INITDB_DATABASE: test_db
   ports:
     - 27017:27017